apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: base-chart
  namespace: identidade-carioca-mapping
spec:
  interval: 1h
  type: oci
  url: oci://ghcr.io/prefeitura-rio/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: identidade-carioca-mapping
  namespace: identidade-carioca-mapping
spec:
  interval: 10m
  chart:
    spec:
      chart: base-chart
      version: 2.4.2
      sourceRef:
        kind: HelmRepository
        name: base-chart
      interval: 1h
  values:
    replicaCount: 2
    fullnameOverride: identidade-carioca-mapping
    image:
      repository: ghcr.io/prefeitura-rio/identidade-carioca-mapping
      tag: sha-dbc5098d2b097ad3bbec0f05edd03f5f0a04698e@sha256:d1f90399608fc212db8995ee7a2edf9dede962f9aa5bd5ee8d7b84e08c1f301c
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 8000
      containerPort: 8080
    resources:
      requests: { memory: 256Mi, cpu: 1000m }
      limits: { memory: 1024Mi, cpu: 2000m }
    healthCheck: { path: /api/v1/readyz }
    podSecurityContext: { fsGroup: 1000 }
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      readOnlyRootFilesystem: true
    envFrom:
      - secretRef: { name: heimdall-secrets }
    infisicalSecret:
      enabled: true
      secretName: heimdall-secrets
      projectSlug: identidade-carioca-mapping-dgl-j
      envSlug: prod
      creationPolicy: Orphan
      universalAuth:
        credentialsRef:
          secretName: universal-auth-credentials
          secretNamespace: infisical-operator-system
    istio:
      enabled: false
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 25
      keda: { enabled: false }
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    podDisruptionBudget:
      enabled: true
      minAvailable: 2
