apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: identidade-carioca-mapping
resources:
  - helmrelease.yaml
  - migration-job.yaml
  - mapping-seed-job.yaml
  - mapping-projection-rebuild-job.yaml
